### ISSUE TITLE
Exception when converting to mp3

### ISSUE THREAD

**Issue by bes1002t** [Ilias95/FF-Multi-Converter#67]
### Description
Try to convert several private concert videos I filmed from h264 mkv to mp3 and the following error occurs everytime:
Traceback (most recent call last):
  File "/usr/lib64/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.10/site-packages/ffmulticonverter/progress.py", line 249, in convert
    if conv_func(*params):
  File "/usr/lib/python3.10/site-packages/ffmulticonverter/progress.py", line 307, in convert_video
    self.nowQPBar.setValue(100 * now_sec / total)
TypeError: setValue(self, int): argument 1 has unexpected type 'float'

### The affected line is:
self.nowQPBar.setValue(100 * now_sec / total)

### Solution
For me it simply worked to cast the calculation result to integer
self.nowQPBar.setValue(int(100 * now_sec / total))

**Comment by ilstam** [comment]
Hi. This has been fixed in master: https://github.com/ilstam/FF-Multi-Converter/commit/c47d47ab7f66a1973b1314ef531de2fb444c2fe6
